import React from 'react'

const ProductDescription = () => {
  return (
    <div className='w-full px-10 md:px-24 lg:px-12 mb-10'>
        <h2 className='font-bold text-xl mb-2'>Description:</h2>
        <hr className='border-1 border-orange-400 mb-4' />
        <p className='text-justify'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nihil magni nam autem odio dignissimos! Beatae aspernatur sapiente sed vel eius quod corporis distinctio voluptas. Minus, dignissimos. Excepturi, officia unde!Loremlorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis modi dolorum reiciendis obcaecati! Alias, iste modi maiores inventore iusto delectus, eligendi doloribus rem consectetur repudiandae quae tenetur nam unde dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, nihil ipsa corrupti, ad commodi facere sed maxime quos deserunt molestiae nam praesentium voluptatem aut incidunt aperiam quam repellat omnis quae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem distinctio illum sunt aut nam ut libero natus accusamus nisi dolores explicabo harum, obcaecati eius ipsa sit aliquid quia porro fugit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore fugiat nesciunt optio doloribus quod repellendus magnam facilis saepe atque velit similique eveniet repellat quia, culpa illo tempora odit voluptates obcaecati.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nihil magni nam autem odio dignissimos! Beatae aspernatur sapiente sed vel eius quod corporis distinctio voluptas. Minus, dignissimos. Excepturi, officia unde!Loremlorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis modi dolorum reiciendis obcaecati! Alias, iste modi maiores inventore iusto delectus, eligendi doloribus rem consectetur repudiandae quae tenetur nam unde dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, nihil ipsa corrupti, ad commodi facere sed maxime quos deserunt molestiae nam praesentium voluptatem aut incidunt aperiam quam repellat omnis quae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem distinctio illum sunt aut nam ut libero natus accusamus nisi dolores explicabo harum, obcaecati eius ipsa sit aliquid quia porro fugit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore fugiat nesciunt optio doloribus quod repellendus magnam facilis saepe atque velit similique eveniet repellat quia, culpa illo tempora odit voluptates obcaecati.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae nihil magni nam autem odio dignissimos! Beatae aspernatur sapiente sed vel eius quod corporis distinctio voluptas. Minus, dignissimos. Excepturi, officia unde!Loremlorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis modi dolorum reiciendis obcaecati! Alias, iste modi maiores inventore iusto delectus, eligendi doloribus rem consectetur repudiandae quae tenetur nam unde dolorem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, nihil ipsa corrupti, ad commodi facere sed maxime quos deserunt molestiae nam praesentium voluptatem aut incidunt aperiam quam repellat omnis quae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem distinctio illum sunt aut nam ut libero natus accusamus nisi dolores explicabo harum, obcaecati eius ipsa sit aliquid quia porro fugit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore fugiat nesciunt optio doloribus quod repellendus magnam facilis saepe atque velit similique eveniet repellat quia, culpa illo tempora odit voluptates obcaecati.
        </p>
    </div>
  )
}

export default ProductDescription